org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = bocchud
mod_name = BoccHUD
author = masa
mod_file_name = bocchud

# Current mod version
mod_version = 0.4.3

# Required malilib version
malilib_version = 0.4.11+mc1.21.10

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 1.21.10
minecraft_version = 1.21.10
mappings_version = 1.21.10+build.2

neoforge_version = 21.10.64
# fabric_api_version = 0.136.0+1.21.10
