org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

loom.platform=neoforge

group = team.cagayakegirls
mod_id = bocchud
mod_name = BoccHUD
author = masa
mod_file_name = bocchud
mod_link = https://github.com/CagayakeGirls/minihud-neoforge

fml_version_range = [4,)
minecraft_version_range = [1.21.2,)
neoforge_version_range = [21.2,)
malilib_version_range = [0.4,)

# Current mod version
mod_version = 0.4.0
version_type = release

# Required malilib version
malilib_version = 0.4.1+mc1.21.3

# Minecraft, NeoForge and mappings versions
minecraft_version_out = 1.21.3
minecraft_version = 1.21.3
mappings_version = 1.21.3+build.2

neoforge_version = 21.3.93
# fabric_api_version = 0.114.1+1.21.3

curseforge_id=916504
modrinth_id=zfPoD7Tm
